blank_issues_enabled: true
contact_links:
  - name: Question
    url: https://discord.gg/foundryvtt
    about: Please ask questions in the Foundry VTT Discord, in the `\#free-league` channel.
  - name: Contact Free League
    url: https://freeleaguepublishing.com/en/contact/
    about: Send a message to Free League for customer support.
  - name: Buy the Roleplaying Game
    url: https://freeleaguepublishing.com/en/games/blade-runner/
    about: A neon-noir wonderland that’ll take your breath away. One way or another. An evocative world of conflicts and contrasts that dares to ask the hard questions and investigate the powers of empathy, the poisons of fear, and the burdens of being human during inhumane times. An iconic and unforgiving playground of endless possibilities that picks you up, slaps you in the face, and tells you to wake up. Time to live. Or time to die.
  - name: Support Us
    url: https://www.patreon.com/Stefouch
    about: Consider supporting me on Patreon!
